services:
  open-drone-core:
    network_mode: host
    privileged: true
    build:
      context: .
    group_add:
      - dialout
      - video
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/open-drone-workspace/open-drone-core
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    working_dir: /open-drone-workspace/open-drone-core
    gpus: all